### PR TITLE
Typing hints and optimisations for v2

### PR DESCRIPTION
**Pull request by Mausy5043**
Probably breaking backwards compatibility (again).
Adding typing hints (by `mypy`) to help improve upstream applications.
Also some code improvements (`black`, `pylint`, `flake8`) and general cleanuping

### CODE REVIEW

**Comment by Mausy5043** [comment]
No conflicts so far.

**Comment by Mausy5043** [comment]
This PR also includes migration to `hatchling` build tool using `pyproject.toml` in stead of `setup.py` and `setup.cfg`.

**Comment by OrbisK** [comment]
> Probably breaking backwards compatibility (again).

for sure :smile:  typing is >=3.10

**Comment by Mausy5043** [comment]
> > Probably breaking backwards compatibility (again).
> 
> for sure 😄 typing is >=3.10

I thought PEP-484 was introduced in 3.5 (https://docs.python.org/3.5/whatsnew/3.5.html)

**Comment by OrbisK** [comment]
> > > Probably breaking backwards compatibility (again).
> > 
> > 
> > for sure 😄 typing is >=3.10
> 
> I thought PEP-484 was introduced in 3.5 (https://docs.python.org/3.5/whatsnew/3.5.html)

sorry, I was in a hurry. i didn't mean typing but `typing.Self` and it's not this PR at all (https://github.com/Mausy5043/bluepy3/pull/23 this is). But `typing.Self` is >=3.11 see https://peps.python.org/pep-0673/

Sorry. I just wanted to comment here in case someone has an issue with python <3.11 (like me). So he/she should know that it's because of the `typing.Self` or python <3.11.

**Comment by Mausy5043** [comment]
I see. Development is on 3.11 according the README, but actually already progressed to 3.12.2 recently. And any type hint suggestions we get from the IDE tend to be incorporated without much thought really. It seems we got a bit too far ahead of ourselves ;-).      
If this is a problem for you then you could open an issue (or better a PR). We don't consider the type hints a critical part, just a convenience for developers of clients. So, we could roll some back or (preferably) import them from `typing_extensions` where appropriate. Especially those that where added after 3.9.

**Pull request merged**
